console.log("Hello node js");
var myName = "Siam Khushnobish";
var myYear = 21.5;
var universitySemester = "7th";
console.log(typeof myName);
console.log(typeof myYear);
console.log(universitySemester);
var youLoveBD = true;
var youLoveIndia = false;
console.log(typeof youLoveBD);
console.log(youLoveIndia);